### ISSUE TITLE
Converting HDF5 data to JSON fails

### ISSUE THREAD

**Issue by rubyvanrooyen** [tart-telescope/notebooks#4]
This issue was detected in the example notebook:    
https://github.com/tart-telescope/notebooks/blob/main/getting_started/TART_cmd_data.ipynb

The command line script `tart_vis2json` needs a little attention, it seems the expected input data format is violated
```
Traceback (most recent call last):
  File "/usr/local/bin/tart_vis2json", line 38, in <module>
    vis_dict = create_direct_vis_dict(vis)
  File "/usr/local/bin/tart_vis2json", line 15, in create_direct_vis_dict
    for (b, v) in zip(vis.baselines, vis.v):
AttributeError: 'str' object has no attribute 'baselines'
```

**Comment by rubyvanrooyen** [comment]
I am going to hold off on this issue, because I think it may be related to investigations currently undertaken by Ben Hugo

**Comment by rubyvanrooyen** [comment]
Just an FYI: I expanded `wsclean_TART_MS` notebook to show `tart2ms` errors more clearly
[wsclean_TART_MS.ipynb](https://github.com/tart-telescope/notebooks/blob/main/application/wsclean_TART_MS.ipynb)

Older example JSON file from repository: `tart2ms --json data_test.json --ms data_test.ms`
```
Traceback (most recent call last):
  File "/usr/local/bin/tart2ms", line 159, in <module>
    ms_from_json(ARGS.ms, ARGS.json, ARGS.pol2,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 1334, in ms_from_json
    ms_create(ms_table_name=ms_name,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 988, in ms_create
    fixms(ms_table_name)
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 310, in fixms
    padded_uvw = synthesize_uvw(station_ECEF=apos,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 182, in synthesize_uvw
    compuvw = dm.to_uvw(dm.baseline(posframe,
  File "/usr/local/lib/python3.8/dist-packages/casacore/measures/__init__.py", line 557, in touvw
    m = _measures.uvw(self, v)
RuntimeError: Cannot convert baseline to uvw: frame information missing
```

Converting online visibilities to JSON: `tart2ms --json {JSON} --ms data_test_1.ms`
```
Traceback (most recent call last):
  File "/usr/local/bin/tart2ms", line 159, in <module>
    ms_from_json(ARGS.ms, ARGS.json, ARGS.pol2,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 1334, in ms_from_json
    ms_create(ms_table_name=ms_name,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 988, in ms_create
    fixms(ms_table_name)
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 310, in fixms
    padded_uvw = synthesize_uvw(station_ECEF=apos,
  File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 182, in synthesize_uvw
    compuvw = dm.to_uvw(dm.baseline(posframe,
  File "/usr/local/lib/python3.8/dist-packages/casacore/measures/__init__.py", line 557, in touvw
    m = _measures.uvw(self, v)
RuntimeError: Cannot convert baseline to uvw: frame information missing
```

**Comment by tmolteno** [comment]
@bennahugo might be best to have a look at this...

**Comment by bennahugo** [comment]
> Just an FYI: I expanded `wsclean_TART_MS` notebook to show `tart2ms` errors more clearly [wsclean_TART_MS.ipynb](https://github.com/tart-telescope/notebooks/blob/main/application/wsclean_TART_MS.ipynb)
> 
> Older example JSON file from repository: `tart2ms --json data_test.json --ms data_test.ms`
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/tart2ms", line 159, in <module>
>     ms_from_json(ARGS.ms, ARGS.json, ARGS.pol2,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 1334, in ms_from_json
>     ms_create(ms_table_name=ms_name,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 988, in ms_create
>     fixms(ms_table_name)
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 310, in fixms
>     padded_uvw = synthesize_uvw(station_ECEF=apos,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 182, in synthesize_uvw
>     compuvw = dm.to_uvw(dm.baseline(posframe,
>   File "/usr/local/lib/python3.8/dist-packages/casacore/measures/__init__.py", line 557, in touvw
>     m = _measures.uvw(self, v)
> RuntimeError: Cannot convert baseline to uvw: frame information missing
> ```
> 
> Converting online visibilities to JSON: `tart2ms --json {JSON} --ms data_test_1.ms`
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/tart2ms", line 159, in <module>
>     ms_from_json(ARGS.ms, ARGS.json, ARGS.pol2,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 1334, in ms_from_json
>     ms_create(ms_table_name=ms_name,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/tart2ms.py", line 988, in ms_create
>     fixms(ms_table_name)
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 310, in fixms
>     padded_uvw = synthesize_uvw(station_ECEF=apos,
>   File "/usr/local/lib/python3.8/dist-packages/tart2ms/fixvis.py", line 182, in synthesize_uvw
>     compuvw = dm.to_uvw(dm.baseline(posframe,
>   File "/usr/local/lib/python3.8/dist-packages/casacore/measures/__init__.py", line 557, in touvw
>     m = _measures.uvw(self, v)
> RuntimeError: Cannot convert baseline to uvw: frame information missing
> ```


@rubyvanrooyen this is not a tart2ms issue - you have to download the casacore data either via rsync (will be most up to date) or via the outdated debian package casacore-data.
```
RUN mkdir -p /usr/share/casacore/data/
WORKDIR /usr/share/casacore/data/
RUN rsync -avz rsync://casa-rsync.nrao.edu/casa-data .
```

**Comment by bennahugo** [comment]
> This issue was detected in the example notebook: https://github.com/tart-telescope/notebooks/blob/main/getting_started/TART_cmd_data.ipynb
> 
> The command line script `tart_vis2json` needs a little attention, it seems the expected input data format is violated
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/tart_vis2json", line 38, in <module>
>     vis_dict = create_direct_vis_dict(vis)
>   File "/usr/local/bin/tart_vis2json", line 15, in create_direct_vis_dict
>     for (b, v) in zip(vis.baselines, vis.v):
> AttributeError: 'str' object has no attribute 'baselines'
> ```

It seems you have two issues though. I've tested this on json files I had at hand (the ones @tmolteno sent me) however it could be that there is a versionning issue between json files. Please attach an example json file where this breaks. Unforunately there is no versionning information available in either the hdf or json files like we have with MeerKAT Visibility Format. This is something only @tmolteno can address

Edit I see the comment is old. I have fixed up the json converter since I believe (there was certainly breakage). Can we please get a test case in to check that this works @tmolteno

**Comment by bennahugo** [comment]
I agree the casacore data thing should be documented somewhere. It is hard enough to follow nrao documentation on the matter of e.g. setting up your casa.rc file

**Comment by bennahugo** [comment]
For good measure I include it here. If you want this data to live somewhere else:
```
cat ${HOME}/.casarc                                                                                     
measures.directory: /usr/share/casacore/data
```
